title: Heladería Jijonenca Prim 212, Barcelona - jijonencasantmarti.com
author: Heladería Jijonenca Prim 212, Barcelona
iam: Heladería Jijonenca Prim 212, Barcelona
email: heladeiajijo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenidos a la página web de la Heladería Jijonenca Prim 212, Barcelona.
keywords: heladería,jijonenca,prim,212,barcelona
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jijonencasantmarti.org" # the base hostname & protocol for your site, e.g. http://example.com

twitter_url:
github_url:
facebook_url: https://www.facebook.com/heladeriajijonencasantmarti
linkedin_url:
instagram_url: https://www.instagram.com/jijonenca_santmarti/

# Tracker
analytics: UA-65020023-1 # Google Analytics

# Build settings
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "blog/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
